workflows:
  android-build:
    name: Compilar APK
    environment:
      java: 17
    scripts:
      - name: Preparar certificado de seguridad
        script: base64 --decode -i debug.keystore.base64 -o debug.keystore
      - name: Descargar e instalar Gradle 9.3.1
        script: |
          curl -sLO https://services.gradle.org/distributions/gradle-9.3.1-bin.zip
          unzip -q gradle-9.3.1-bin.zip
      - name: Compilar instalador APK
        script: ./gradle-9.3.1/bin/gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
